### ISSUE TITLE
官方案例请求失败，

### ISSUE THREAD

**Issue by AkatsukiNoKag** [volcengine/ve-tos-dotnet-sdk#10]
为什么使用官方的案例https://www.volcengine.com/docs/6349/1130419
会请求失败？

var listBucketsOutput = client.ListBuckets();
返回码0003-00000001

而请求桶信息是正确的。
var headBucketOutput = client.HeadBucket(headBucketInput);

**Comment by zstdxxf** [comment]
权限不足，参见 https://www.volcengine.com/docs/6349/1130419 注意事项，添加权限

**Comment by ghost** [comment]
权限不足，参见 https://www.volcengine.com/docs/6349/1130419 注意事项，添加权限

**Comment by isqyz** [comment]
> 权限不足，参见https://www.volcengine.com/docs/6349/1130419注意事项，添加权限

用的就是这个案例
